config/routes.rb
Transparencia::Application.routes.draw do

  resources :monthlies
  resources :travel_expenses
  resources :travel_drivers
  resources :travels
  resources :vehicles
  resources :drivers
  resources :participants
  resources :confirmations
  resources :requests
  resources :addresses
  resources :user_types
  resources :reserve_of_physical_spaces
  resources :reservation_statuses
  resources :alocation_permanents
  resources :spaces
  resources :location_types
  resources :semesters
  resources :recesses
  resources :holidays
  resources :request_users

  root to: 'users#login'

  # resources :administrators
  get '/administrator/login' => 'administrators#login', as: :administrator_login
  get '/administrator/logout' => 'administrators#logout', as: :administrator_logout
  get '/administrator/welcome' => 'administrators#welcome', as: :administrator_welcome
  post '/administrator/authentication' => 'administrators#authentication', as: :administrator_authentication
  post '/administrator/create' => 'administrators#create', as: :administrator_create
  get '/administrator/new' => 'administrators#new', as: :administrator_new

  #páginas de erro
  get '/notfound' => 'portal#notfound', as: :notfound
  
  resources :users do
    resources :durations
  end

  resources :roles
  resources :sectors
  resources :institutions
  resources :functions
  resources :locals
  resources :dailies
  resources :durations
  resources :daily_function_locals

  resources :amounts do
    resources :readjustments
  end

  resources :readjustments
  resources :requests

  get 'alocation_permanents/space/:semester_id/espacos' => 'alocation_permanents#espacos', as: 'alocation_permanents_espacos'
  get 'alocation_permanents/space/:id/:semester_id' => 'alocation_permanents#reserves', as: 'alocation_permanents_space'
  get 'alocation_permanents/space/:id/:semester_id/edit' => 'alocation_permanents#editar', as: 'alocation_permanents_editar'
  post 'alocation_permanents/spaces/:space_id/:semester_id/salvar_alocacao' => 'alocation_permanents#salvar_alocacao', as: 'salvar_alocacao'

  get 'reserve_of_physical_spaces/space/all' => 'reserve_of_physical_spaces#espacos', as: 'reserve_of_physical_spaces_espacos'
  get 'reserve_of_physical_spaces/space/:id' => 'reserve_of_physical_spaces#reservas', as: 'reserve_of_physical_spaces_reservas'
  get 'reserve_of_physical_spaces/space/:id/:mes/:ano' => 'reserve_of_physical_spaces#calendario', as: 'calendario'

  get 'reserve/space/:id/:mes/:ano/new' => 'reserve_of_physical_spaces#new', as: 'reserve_of_physical_spaces_reservas_new'
  
  get '/reserve_of_physical_spaces/aprovacoes/list' => 'reserve_of_physical_spaces#aprovacoes', as: 'aprovacoes'
  get '/reserve_of_physical_spaces/approve/:id' => 'reserve_of_physical_spaces#approve', as: 'approve_reserves'
  get '/reserve_of_physical_spaces/non_approve/:id' => 'reserve_of_physical_spaces#non_approve', as: 'non_approve_reserves'
  post '/create/:id/:mes/:ano/reserve_of_physical_space' => 'reserve_of_physical_spaces#create', as: 'create_reserve'
  post '/update/reserve_of_physical_space/:id' => 'reserve_of_physical_spaces#update', as: 'update_reserve'
  #post 'alocation_permanents/spaces/salvar_alocacao' => 'alocation_permanents#salvar_alocacao', as: 'salvar_alocacao'

  #rotas de users
  get '/user/login' => 'users#login', as: 'user_login'
  get '/user/logout' => 'users#logout', as: 'user_logout'
  post '/user/authentication' => 'users#authentication', as: 'user_authentication'
  get '/user/profile/edit' => 'users#edit_profile', as: 'edit_user_profile'
  get '/user/profile/edit/password' => 'users#edit_password', as: 'edit_user_password'
  post '/user/profile/update' => 'users#update_profile', as: 'update_user_profile'
  post '/user/profile/update/password' => 'users#update_password', as: 'update_user_password'

  
  #rotas de confirmations
  get '/confirmations/approve/:id' => 'confirmations#approve', as: 'approve_request'
  post '/confirmations/non_approve/:id' => 'confirmations#non_approve', as: 'non_approve_request'
  get '/confirmations/jus_non_approve/:id' => 'confirmations#non_approve_form', as: 'non_approve_form_request'

  #rota de participants para adicionar users a viagem 
  get '/participants/add/request/:id' => 'participants#index' ,as: 'add_participants'
  post '/participants/add/request/:id' => 'participants#add_participants' ,as: 'add_participants'
   
  #rota para solicitação
  get '/request/user' => 'requests#request_users', as: 'request_users'

  #rotas de confirmações
  get '/confirmations/:id/travel' => 'confirmations#travel', as: 'confirmation_travel'
  get '/confirmations/request/:id/travel/new' => 'travels#new', as: 'confirmation_new_travel'
  get '/confirmations/request/:id/travel/edit' => 'travels#edit', as: 'confirmation_edit_travel'
  get '/confirmations/:id/travel/show' => 'confirmations#show_travel', as: 'confirmation_show_travel'



  #rotas para adicionar motoristas a viagem
  get '/travels/:id/travel_drivers' => 'travel_drivers#index', as: 'add_driver'
  post '/travels/:id/travel_drivers' => 'travel_drivers#add_drivers', as: 'add_driver'
  resources :reserve_of_physical_spaces

  get '/relatorios/lista-de-veiculos' => 'reports#imprimir_veiculos', as: 'imprimir_veiculos'
  
  get '/home' => 'portal#index', as: 'home'
  get '/home/patrimonio' => 'portal#home_patrimonio', as: 'home_patrimonio'
  get '/home/transporte' => 'portal#home_transporte', as: 'home_transporte'
end

app/models/holiday.rb
#encoding: utf-8
class Holiday < ActiveRecord::Base
  attr_accessible :deleted, :date, :day, :description, :fixed, :month

  
  validates :description, presence: true


  validates :verificar_inteiros, acceptance: {accept: true, message: 'Data não é válida'}

  before_save do |holiday|
    holiday.date = nil if holiday.fixed
    holiday.day = nil && holiday.month = nil if holiday.fixed == false
  end

  
  def verificar_inteiros
  	ok = true
  	if self.fixed
        ok = false unless self.day
        ok = false if self.day && (self.day > 31 || self.day < 1)
        ok = false unless self.month
        ok = false if self.month && (self.month > 12 || self.month < 1)
  	end

    return ok
  end
end	

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  
  include UsersHelper
  include ApplicationHelper

  # before_filter :autorizacao_chefe_setor_patrimonio, except: []
  
  def index
    @holidays = Holiday.where(deleted: false)
  end

  def show
    @holiday = Holiday.find(params[:id])
  end

  def new
    @holiday = Holiday.new
  end

  def edit
    @holiday = Holiday.find(params[:id])
    @holiday.date = format_date_br(@holiday.date)
  end

  def create
    @holiday = Holiday.new(params[:holiday])
    @holiday.deleted = false
    
    if @holiday.save
      redirect_to holidays_path
    else
      render :new  
    end
  end

  def update
    @holiday = Holiday.find(params[:id])

    if @holiday.update_attributes(params[:holiday])
      redirect_to holidays_path
    else
      render :edit
    end
  end

  def destroy
    @holiday = Holiday.find(params[:id])
    @holiday.update_attribute(:deleted, true)
    redirect_to holidays_path
  end
end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/views/holidays/_form.html.erb
<%= form_for(@holiday) do |f| %>
  <% if @holiday.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @holiday.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="espacamento">
    <div class="field">
      <%= f.label :description %>
      <%= f.text_field :description, autofocus: 'autofocus' %>
    </div>
    <div class="field">
      <%= f.label :day %>
      <%= f.number_field :day, class: 'fixo' %>
    </div>
    <div class="field">
      <%= f.label :month %>
      <%= f.number_field :month, class: 'fixo' %>
    </div>
    <div class="field">
      <%= f.label :fixed %>
      <%= f.check_box :fixed, id: 'fixo' %>
    </div>
    <div class="field">
      <%= f.label :date %>
      <%= f.text_field :date, class: 'datepicker', placeholder: 'dd/mm/aaaa' %>
    </div>
</div>
<% end %>


<script type="text/javascript">
  $('.salvar').click(function() {
    $('form').submit();
  });
</script>


<script type="text/javascript">

function desabilitar() {
  if ($("#fixo").prop('checked'))
  {
    $(".nao-fixo").prop('disabled', true);
    $(".fixo").prop('disabled', false);
  }else{
    $(".nao-fixo").prop('disabled', false);
    $(".fixo").prop('disabled', true);
  }
}

desabilitar();

$("#fixo").click(function() {
  desabilitar();
});

</script>

app/views/holidays/edit.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="#">Editando feriado</a>
    <ul class="nav">
      <li><%= link_to 'Salvar', '#', class: 'salvar' %></li>
      <li><%= link_to 'Cancelar', holidays_path %></li>
    </ul>
  </div>
</div>

<%= render 'form' %>

app/views/holidays/index.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="#">Feriados</a>
    <ul class="nav">
      <li><%= link_to 'Criar novo', new_holiday_path %></li>
    </ul>
  </div>
</div>

<div class="espacamento">
  <table class="table table-hover">
    <tr>
      <th>Descrição</th>
      <th>Dia</th>
      <th>Mês</th>
      <th>Fixo</th>
      <th>Data</th>
      <th width="80">Ações</th>
    </tr>

  <% @holidays.each do |holiday| %>
    <tr>
      <td><%= holiday.description %></td>
      <td><%= holiday.day %></td>
      <td><%= holiday.month %></td>
      <td><%= frendly_boolean holiday.fixed %></td>
      <td><%= format_date_br holiday.date %></td>
      <td>
          <%= link_to edit_holiday_path(holiday), title: 'Editar' do %><i class="icon-edit"></i><% end %>
          <%= link_to holiday, method: :delete, data: { confirm: 'Você tem certeza?' }, title: 'Remover' do %> <i class="icon-trash"></i> <% end %>
      </td>
    </tr>
  <% end %>
  </table>
</div>

app/views/holidays/new.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="#">Novo feriado</a>
    <ul class="nav">
      <li><%= link_to 'Salvar', '#', class: 'salvar' %></li>
      <li><%= link_to 'Cancelar', holidays_path %></li>
    </ul>
  </div>
</div>

<%= render 'form' %>

app/views/holidays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @holiday.description %>
</p>

<p>
  <b>Day:</b>
  <%= @holiday.day %>
</p>

<p>
  <b>Month:</b>
  <%= @holiday.month %>
</p>

<p>
  <b>Fixed:</b>
  <%= @holiday.fixed %>
</p>

<p>
  <b>Date:</b>
  <%= @holiday.date %>
</p>