config/routes.rb
Transparencia::Application.routes.draw do

  resources :monthlies
  resources :travel_expenses
  resources :travel_drivers
  resources :travels
  resources :vehicles
  resources :drivers
  resources :participants
  resources :confirmations
  resources :requests
  resources :addresses
  resources :user_types
  resources :reserve_of_physical_spaces
  resources :reservation_statuses
  resources :alocation_permanents
  resources :spaces
  resources :location_types
  resources :semesters
  resources :recesses
  resources :holidays
  resources :request_users

  root to: 'users#login'

  # resources :administrators
  get '/administrator/login' => 'administrators#login', as: :administrator_login
  get '/administrator/logout' => 'administrators#logout', as: :administrator_logout
  get '/administrator/welcome' => 'administrators#welcome', as: :administrator_welcome
  post '/administrator/authentication' => 'administrators#authentication', as: :administrator_authentication
  post '/administrator/create' => 'administrators#create', as: :administrator_create
  get '/administrator/new' => 'administrators#new', as: :administrator_new

  #páginas de erro
  get '/notfound' => 'portal#notfound', as: :notfound
  
  resources :users do
    resources :durations
  end

  resources :roles
  resources :sectors
  resources :institutions
  resources :functions
  resources :locals
  resources :dailies
  resources :durations
  resources :daily_function_locals

  resources :amounts do
    resources :readjustments
  end

  resources :readjustments
  resources :requests

  get 'alocation_permanents/space/:semester_id/espacos' => 'alocation_permanents#espacos', as: 'alocation_permanents_espacos'
  get 'alocation_permanents/space/:id/:semester_id' => 'alocation_permanents#reserves', as: 'alocation_permanents_space'
  get 'alocation_permanents/space/:id/:semester_id/edit' => 'alocation_permanents#editar', as: 'alocation_permanents_editar'
  post 'alocation_permanents/spaces/:space_id/:semester_id/salvar_alocacao' => 'alocation_permanents#salvar_alocacao', as: 'salvar_alocacao'

  get 'reserve_of_physical_spaces/space/all' => 'reserve_of_physical_spaces#espacos', as: 'reserve_of_physical_spaces_espacos'
  get 'reserve_of_physical_spaces/space/:id' => 'reserve_of_physical_spaces#reservas', as: 'reserve_of_physical_spaces_reservas'
  get 'reserve_of_physical_spaces/space/:id/:mes/:ano' => 'reserve_of_physical_spaces#calendario', as: 'calendario'

  get 'reserve/space/:id/:mes/:ano/new' => 'reserve_of_physical_spaces#new', as: 'reserve_of_physical_spaces_reservas_new'
  
  get '/reserve_of_physical_spaces/aprovacoes/list' => 'reserve_of_physical_spaces#aprovacoes', as: 'aprovacoes'
  get '/reserve_of_physical_spaces/approve/:id' => 'reserve_of_physical_spaces#approve', as: 'approve_reserves'
  get '/reserve_of_physical_spaces/non_approve/:id' => 'reserve_of_physical_spaces#non_approve', as: 'non_approve_reserves'
  post '/create/:id/:mes/:ano/reserve_of_physical_space' => 'reserve_of_physical_spaces#create', as: 'create_reserve'
  post '/update/reserve_of_physical_space/:id' => 'reserve_of_physical_spaces#update', as: 'update_reserve'
  #post 'alocation_permanents/spaces/salvar_alocacao' => 'alocation_permanents#salvar_alocacao', as: 'salvar_alocacao'

  #rotas de users
  get '/user/login' => 'users#login', as: 'user_login'
  get '/user/logout' => 'users#logout', as: 'user_logout'
  post '/user/authentication' => 'users#authentication', as: 'user_authentication'
  get '/user/profile/edit' => 'users#edit_profile', as: 'edit_user_profile'
  get '/user/profile/edit/password' => 'users#edit_password', as: 'edit_user_password'
  post '/user/profile/update' => 'users#update_profile', as: 'update_user_profile'
  post '/user/profile/update/password' => 'users#update_password', as: 'update_user_password'

  
  #rotas de confirmations
  get '/confirmations/approve/:id' => 'confirmations#approve', as: 'approve_request'
  post '/confirmations/non_approve/:id' => 'confirmations#non_approve', as: 'non_approve_request'
  get '/confirmations/jus_non_approve/:id' => 'confirmations#non_approve_form', as: 'non_approve_form_request'

  #rota de participants para adicionar users a viagem 
  get '/participants/add/request/:id' => 'participants#index' ,as: 'add_participants'
  post '/participants/add/request/:id' => 'participants#add_participants' ,as: 'add_participants'
   
  #rota para solicitação
  get '/request/user' => 'requests#request_users', as: 'request_users'

  #rotas de confirmações
  get '/confirmations/:id/travel' => 'confirmations#travel', as: 'confirmation_travel'
  get '/confirmations/request/:id/travel/new' => 'travels#new', as: 'confirmation_new_travel'
  get '/confirmations/request/:id/travel/edit' => 'travels#edit', as: 'confirmation_edit_travel'
  get '/confirmations/:id/travel/show' => 'confirmations#show_travel', as: 'confirmation_show_travel'



  #rotas para adicionar motoristas a viagem
  get '/travels/:id/travel_drivers' => 'travel_drivers#index', as: 'add_driver'
  post '/travels/:id/travel_drivers' => 'travel_drivers#add_drivers', as: 'add_driver'
  resources :reserve_of_physical_spaces

  get '/relatorios/lista-de-veiculos' => 'reports#imprimir_veiculos', as: 'imprimir_veiculos'
  
  get '/home' => 'portal#index', as: 'home'
  get '/home/patrimonio' => 'portal#home_patrimonio', as: 'home_patrimonio'
  get '/home/transporte' => 'portal#home_transporte', as: 'home_transporte'
end

app/controllers/reserve_of_physical_spaces_controller.rb
#encoding: utf-8
class ReserveOfPhysicalSpacesController < ApplicationController

  include ReserveOfPhysicalSpacesHelper
  include UsersHelper
  include ApplicationHelper

  # before_filter :autorizacao_chefe_setor_patrimonio, only: [:aprovacoes]

  def index
    @reserve_of_physical_spaces = ReserveOfPhysicalSpace.where(deleted: false, user_id: session[:user].id).order("id DESC")
  end
  
  def espacos
    @spaces = Space.where(deleted: false)
  end
  
  def reservas
    @reserves = AlocationPermanent.where(deleted: false, space_id: params[:id])
    
    @id = params[:id]
    #@reserves = AlocationPermanent.where(deleted: false)
    @array = Array.new(16).map {|e| e = Array.new(31).map {|ee| e = '---' } }

    @reserves.each do |r|
     @array[r.schedule][r.week_day] = 'FIXA'
     @array[r.schedule][r.week_day+7] = 'FIXA'
     @array[r.schedule][r.week_day+14] = 'FIXA'
     @array[r.schedule][r.week_day+21] = 'FIXA'
    end
  end

  def calendario
    mes = params[:mes].to_i
    ano = params[:ano].to_i
    @space = Space.find(params[:id])
    @id = params[:id]
    semester = Semester.where(deleted: false)
    @reserves = []

    semester.each do |s|
      if (s.start_date.year == ano && s.end_date.year == ano) && (mes >= s.start_date.month && mes <= s.end_date.month)
        @reserves = AlocationPermanent.where(deleted: false, space_id: params[:id], semester_id: s.id)        
      elsif (s.start_date.year < ano) && (s.end_date.year == ano) && (mes <= s.end_date.month)
        @reserves = AlocationPermanent.where(deleted: false, space_id: params[:id], semester_id: s.id)
      elsif (s.start_date.year == ano) && (mes >= s.start_date.month)
        @reserves = AlocationPermanent.where(deleted: false, space_id: params[:id], semester_id: s.id)
      end
    end

    @holiday_fixeds = Holiday.where(deleted: false, fixed: true, month: mes)
    @holiday_move = Holiday.where(deleted: false, fixed: false)
    
    @holiday_move = @holiday_move.select { |h| h.date.year == ano }

    @recesso = Recess.where(deleted: false)
    @reserve_of_physical_spaces = ReserveOfPhysicalSpace.where(deleted: false, space_id: params[:id], reservation_status_id: 1)

    @recesso = @recesso.select {|h| h.begin.month == mes || h.end.month == mes }

    @holiday_move = @holiday_move.select {|h| h.date.month == mes} 

    @reserve_of_physical_spaces = @reserve_of_physical_spaces.select {|r| r.date.month == mes && r.date.year == ano}

    x = DateTime.new(ano, mes, 1)
    @qtd_dias_mes = x.end_of_month.day
    @ano = ano
    @mes = mes
    @array = Array.new(16).map {|e| e = Array.new(@qtd_dias_mes).map {|ee| e = '' } }
    
    @reserves.each do |r|
        a = dias_reserva_fixa(mes, ano, r.week_day, @qtd_dias_mes, r.semester.start_date, r.semester.end_date)
        a.each do |w|
          @array[r.schedule][w-1] = r
        end
    end
    
    @recesso.each do |r|
      if r.begin.day >= 1 && r.end.day <= @qtd_dias_mes && (r.begin.year == ano || r.end.year == ano)
        for i in (r.begin.day .. r.end.day)
          for j in (0..15)
            @array[j][i-1] = r
          end
        end
      end

      if (r.begin.year == ano && r.end.year == ano) && (r.begin.month == mes && r.end.month != mes)
         for i in (r.begin.day .. @qtd_dias_mes)
           for j in (0..15)
             @array[j][i-1] = r
           end
         end
      end

      if (r.begin.year == ano && r.end.year == ano) && (r.begin.month != mes && r.end.month == mes)
         for i in (1 .. r.end.day)
           for j in (0..15)
             @array[j][i-1] = r
           end
         end
      end
      

      if (((r.end.day >= 1 && r.begin.month < mes && r.begin.year == ano) || (r.end.day >= 1 && r.begin.month > mes && r.begin.year < ano)) && (r.begin.year == ano - 1))
        for i in (1 .. r.end.day)
          for j in (0..15)
            @array[j][i-1] = r
          end
        end
      end

      if (((r.begin.day >= 1 && r.end.month > mes && r.end.year == ano) || (r.begin.day >= 1 && r.end.month < mes && r.end.year > ano)) && (r.end.year == ano + 1))
        for i in (r.begin.day .. @qtd_dias_mes)
          for j in (0..15)
            @array[j][i-1] = r
          end
        end
      end
    end

    @holiday_fixeds.each do |h|
      for i in (0..15)
        @array[i][h.day - 1] = h
      end
    end


    @holiday_move.each do |h|
      for i in (0..15)
        @array[i][h.date.day - 1] = h
      end
    end
    

    @reserve_of_physical_spaces.each do |r|
      for i in (r.start_time .. r.end_time)
        @array[i][r.date.day - 1] = r
      end
    end
  end

  def show
    @reserve_of_physical_space = ReserveOfPhysicalSpace.find(params[:id])
  end

  def new
    @mes = params[:mes].to_i
    @ano = params[:ano].to_i
    @id = params[:id].to_i
    @reserve_of_physical_space = ReserveOfPhysicalSpace.new(space_id: params[:id])
  end

  def edit
    @reserve_of_physical_space = ReserveOfPhysicalSpace.find(params[:id])
    redirect_to notfound_path if session[:user].id != @reserve_of_physical_space.user_id
    @reserve_of_physical_space.date = format_date_br(@reserve_of_physical_space.date)
  end

  def create
    @mes = params[:mes].to_i
    @ano = params[:ano].to_i
    @id = params[:id].to_i
    
    @reserve_of_physical_space = ReserveOfPhysicalSpace.new(params[:reserve_of_physical_space])
    @reserve_of_physical_space.price = Space.find(@reserve_of_physical_space.space_id).price_local
    @reserve_of_physical_space.deleted = false
    @reserve_of_physical_space.payment_confirmed = false
    @reserve_of_physical_space.user_id = session[:user].id
    @reserve_of_physical_space.reservation_status_id = 2
    
    if @reserve_of_physical_space.save
      redirect_to reserve_of_physical_spaces_path
    else
      render :new
    end
  end

  def aprovacoes
    @reserves = ReserveOfPhysicalSpace.where(deleted: false).order("id DESC")
  end

  def approve
    @reserva = ReserveOfPhysicalSpace.find(params[:id])

    reserves = ReserveOfPhysicalSpace.where(deleted: false, space_id: @reserva.space_id)
    reserves = reserves.select {|reserve| (@reserva.date.day == reserve.date.day && @reserva.date.month == reserve.date.month && @reserva.date.year == reserve.date.year) && ((reserve.start_time >= @reserva.start_time && reserve.start_time <= @reserva.end_time)||(reserve.end_time >= @reserva.start_time && reserve.end_time <= @reserva.end_time)) && reserve.reservation_status_id ==1}

    if reserves.empty? 
      @reserva.update_attribute(:reservation_status_id, 1)
    else
      flash[:error] = 'Esse espaço já está reservado'
    end

    redirect_to aprovacoes_path
  end

  def non_approve
    @reserva = ReserveOfPhysicalSpace.find(params[:id])
    @reserva.update_attribute(:reservation_status_id, 3)
    redirect_to aprovacoes_path
  end

  def update
    @reserve_of_physical_space = ReserveOfPhysicalSpace.find(params[:id])
    redirect_to notfound_path if session[:user].id != @reserve_of_physical_space.user_id
    if @reserve_of_physical_space.reservation_status_id == 2
      if @reserve_of_physical_space.update_attributes(params[:reserve_of_physical_space])
        redirect_to reserve_of_physical_spaces_path
      else
        render :edit  
      end
    else
      flash[:error] = 'Não é possível modificar uma reserva confirmada ou cancelada'
      render :edit
    end
  end

  def destroy
    @reserve_of_physical_space = ReserveOfPhysicalSpace.find(params[:id])
    @reserve_of_physical_space.update_attribute(:deleted, true)
    redirect_to reserve_of_physical_spaces_path
  end
end

app/helpers/reserve_of_physical_spaces_helper.rb
#encoding: utf-8
module ReserveOfPhysicalSpacesHelper

  def tipo_objeto(objeto)
    return "feriado-recesso" if objeto.class.to_s == "Recess" || objeto.class.to_s == "Holiday"
    return "alocacao-permanente" if objeto.class.to_s == "AlocationPermanent"
    return "reserva-usuario" if objeto.class.to_s == "ReserveOfPhysicalSpace"
    return ""
  end

	def schedules
  	a = [
  		'06:00 - 07:00',
  		'07:00 - 08:00',
  		'08:00 - 09:00',
  		'09:00 - 10:00',
  		'10:00 - 11:00',
  		'11:00 - 12:00',
  		'12:00 - 13:00',
  		'13:00 - 14:00',
  		'14:00 - 15:00',
  		'15:00 - 16:00',
  		'16:00 - 17:00',
  		'17:00 - 18:00',
  		'18:00 - 19:00',
  		'19:00 - 20:00',
  		'20:00 - 21:00',
  		'21:00 - 22:00']
  end

  def months
    a = [
      'Janeiro',
      'Fevereiro',
      'Março',
      'Abril',
      'Maio',
      'Junho',
      'Julho',
      'Agosto',
      'Setembro',
      'Outubro',
      'Novembro',
      'Dezembro'
    ]
  end

  def dias_reserva_fixa(mes, ano, week_day, qtdDias, inicio_semestre, fim_semestre)
     #reserves = AlocationPermanent.where(deleted: false, space_id: params[:id])
     array = Array.new

     for i in (1..qtdDias)
       x = DateTime.new(ano, mes, i)
       array << i if week_day == x.wday && x >= inicio_semestre && x <= fim_semestre

     end 

     array
  end


def mes_anterior(mes, ano)
  m = nil
  a = ano
  if mes > 1
    m = mes - 1
  else
    m = 12
    a = ano -1
  end
  return m, a
end

#mes, ano = mes_anterior(@mes, @ano)

def mes_seguinte(mes, ano)
  m = nil
  a = ano
  if mes < 12
    m = mes + 1
  else
    m = 1
    a = ano + 1
  end
  return m,a
end


def customizar_aaah!(reserve)
  if reserve == 1
    return "success"
  end

  if reserve == 3
    return "warning"
  end

  return ""
end




end

app/views/reserve_of_physical_spaces/aprovacoes.html.erb
<% unless flash.empty? %>
  <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <h3><%= flash[:error] %></h3>
  </div>
<% end %>

<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="#">Aprovar Reservas</a>
    <ul class="nav">
      
    </ul>
  </div>
</div>

<div class="espacamento">
    <table class="table table-hover">
      <tr>
        <th>Data</th>
        <th>Usuário</th>
        <th>evento</th>
        <th>Horário de Início</th>
        <th>Horário de Saída</th>
        <th>Justificativa</th>
        <th>Espaço</th>
        <th>Status da Reserva</th>
        <th>Opções</th>
      </tr>

    <% @reserves.each do |reserve| %>
      <tr class="<%= customizar_aaah!(reserve.reservation_status_id) %>">
        <td><%= format_date_br reserve.date %></td>
        <td><%= reserve.user.name %></td>
        <td><%= reserve.event %></td>
        <td><%= schedules[reserve.start_time] %></td>
        <td><%= schedules[reserve.end_time] %></td>
        <td>
            <!-- Link para abrir a janela de dialogo modal -->
          <a href="#justification_<%= reserve.id %>" role="button" data-toggle="modal">Exibir</a>
          <!-- janela de dialogo modal -->
          <div id="justification_<%= reserve.id %>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
              <h3 id="myModalLabel_<%= reserve.id %>">Justificativa</h3>
            </div>
            <div class="modal-body">
              <p><%= reserve.justification %></p>
            </div>
          </div>
          <!-- fim da janela de dialogo modal -->

        </td>
        <td><%= reserve.space.location_type.name %> <%= reserve.space.name %></td>
        <td><%= reserve.reservation_status.name %></td>
        <td>
            <%= link_to approve_reserves_path(reserve.id), title: 'Aprovar' do %><i class="icon-ok" ></i><%end%>
            <%= link_to non_approve_reserves_path(reserve.id), title: 'Não Aprovar' do %><i class="icon-remove"></i><%end%>
        </td>
      </tr>
    <% end %>
    </table>
</div>

app/views/reserve_of_physical_spaces/calendario.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="#"><%= @space.location_type.name %> <%= @space.name %></a>
    <ul class="nav">
      <li><%= link_to 'Nova reserva', reserve_of_physical_spaces_reservas_new_path(@id,@mes,@ano) %></li>
      <% mes, ano = mes_anterior(@mes,@ano) %>
      <li><%= link_to 'Mês anterior', calendario_path(@id,mes,ano)%></li>
      <% mes, ano = mes_seguinte(@mes,@ano) %>
      <li><%= link_to 'Mês seguinte', calendario_path(@id,mes,ano) %></li>
      <li><%= link_to 'Voltar', reserve_of_physical_spaces_espacos_path %></li>
    </ul>
  </div>
</div>

<h1>Reservas de <%= months[@mes-1] %> de <%= @ano %></h1>
<br>
<div class="row">
<div class="span11">
  
 <table class="tabela">
 	<tr>
 		<th>Horário</th>
      <% for i in (1..@qtd_dias_mes) %>
 		    <th class="aumentar-largura"><center><%= i %></center></th>
      <% end %>

 	</tr>
  <% for i in (0..15) %>
  <tr>
    <th><%= schedules[i] %></th>
    <% for j in (0..@qtd_dias_mes-1) %>
        <% x = tipo_objeto @array[i][j] %>
      	<td class="<%= x %>">
        <% if x == 'reserva-usuario' %>
          <!-- Link para abrir a janela de dialogo modal -->
          <a href="#reserve_<%= @array[i][j].id %>" role="button" data-toggle="modal"><i class="icon-user"></i></a>
          <!-- janela de dialogo modal -->
          <div id="reserve_<%= @array[i][j].id %>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
              <h3 id="myModalLabel_<%= @array[i][j].id %>">Detalhes</h3>
            </div>
            <div class="modal-body">
              <p><strong>Usuário:</strong> <%= @array[i][j].user.name %></p>
              <p><strong>Evento:</strong> <%= @array[i][j].event %></p>
              <p><strong>Justificativa:</strong> <%= @array[i][j].justification %></p>
            </div>
          </div>
          <!-- fim da janela de dialogo modal -->
        <% end %>
        </td>
    <% end %>
  </tr>
  <% end %>
 </table>

</div>


<div class="span3">


<table class="tabela">
  <tr>
    <td><strong>Cor</strong></td>
    <td><strong>Significado</strong></td>
  </tr>
  <tr>
    <td class="feriado-recesso"></td>
    <td>Feriado/Recesso</td>
  </tr>
  <tr>
    <td class="alocacao-permanente"></td>
    <td>Reservas fixas</td>
  </tr>
  <tr>
    <td class="reserva-usuario"></td>
    <td>Reservas de usuários</td>
  </tr>
</table>

</div>
</div>

app/views/reserve_of_physical_spaces/espacos.html.erb
<% x = DateTime.now %>

<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="#">Espaços Físicos</a>
  </div>
</div>

<div class="espacamento">
<table class="table table-hover">
  <tr>
    <th>Nome</th>
    <th>Capacidade</th>
    <th>Tamanho</th>
    <th>Tipo do Local</th>
    <th>Ações</th>
  </tr>

<% @spaces.each do |space| %>
  <tr>
    <td><%= space.name %></td>
    <td><%= space.capacity %></td>
    <td><%= space.size %></td>
    <td><%= space.location_type.name %></td>
    <td><%= link_to 'Reservar', calendario_path(space.id, x.month, x.year) %></td>
  </tr>
<% end %>
</table>
</div>

app/views/reserve_of_physical_spaces/index.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="#">Minhas Reservas</a>
    <ul class="nav">
      <li><%= link_to 'Criar nova', reserve_of_physical_spaces_espacos_path %></li>
    </ul>
  </div>
</div>

<div class="espacamento">
<table class="table table hover">
  <tr>
    <th>Data</th>
    <th>Horário de Inicio</th>
    <th>Horário de Fim</th>
    <th>Evento</th>
    <th>Justificativa</th>
    <th>Valor</th>
    <th>Pagamento Confirmado</th>
    <th>Espaço</th>
    <th>Status da Reserva</th>
    <th>Ações</th>
  </tr>

<% @reserve_of_physical_spaces.each do |reserve_of_physical_space| %>
  <tr class="<%= customizar_aaah!(reserve_of_physical_space.reservation_status_id) %>">
    <td><%= format_date_br reserve_of_physical_space.date %></td>
    <td><%= schedules[reserve_of_physical_space.start_time] %></td>
    <td><%= schedules[reserve_of_physical_space.end_time] %></td>
    <td><%= reserve_of_physical_space.event %></td>
    <td>
      <!-- Link para abrir a janela de dialogo modal -->
      <a href="#justification_<%= reserve_of_physical_space.id %>" role="button" data-toggle="modal">Exibir</a>
      <!-- janela de dialogo modal -->
      <div id="justification_<%= reserve_of_physical_space.id %>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h3 id="myModalLabel_<%= reserve_of_physical_space.id %>">Justificativa</h3>
        </div>
        <div class="modal-body">
          <p><%= reserve_of_physical_space.justification %></p>
        </div>
      </div>
      <!-- fim da janela de dialogo modal -->

    </td>
    <td><%= reserve_of_physical_space.price %></td>
    <td><%= frendly_boolean reserve_of_physical_space.payment_confirmed %></td>
    <td><%= reserve_of_physical_space.space.name %></td>
    <td><%= reserve_of_physical_space.reservation_status.name %></td>
    <td>
       <%= link_to reserve_of_physical_space, title: 'Detalhes' do %> <i class="icon-list"></i><%end%>
       <%= link_to edit_reserve_of_physical_space_path(reserve_of_physical_space), title: 'Editar' do %> <i class="icon-edit"></i><%end%>
       <%= link_to reserve_of_physical_space, method: :delete, data: { confirm: 'Você tem certeza?'}, title: 'Excluir' do %> <i class="icon-trash"></i><%end%>
    </td>
  </tr>
<% end %>
</table>
</div>

app/views/reserve_of_physical_spaces/new.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="#">Nova Reserva</a>
    <ul class="nav">
      <li><%= link_to 'Salvar', '#', class: 'salvar' %></li>
      <li><%= link_to 'Cancelar', calendario_path(@id,@mes,@ano) %></li>
    </ul>
  </div>
</div>

<%= form_for @reserve_of_physical_space, url: create_reserve_path(@id,@mes,@ano), method: 'post' do |f| %>

  <% if @reserve_of_physical_space.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @reserve_of_physical_space.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="espacamento">
  <div class="field">
    <%= f.label :date %>
    <%= f.text_field :date, class: 'datepicker', placeholder: 'dd/mm/aaaa' %>
  </div>
  <div class="field">
    <%= f.label :start_time %>
    <%# f.text_field :start_time %>
    <%= f.select :start_time, schedules_select, prompt: true %>
  </div>
  <div class="field">
    <%= f.label :end_time %>
    <%= f.select :end_time, schedules_select, prompt: true %>
  </div>
  <div class="field">
    <%= f.label :event %>
    <%= f.text_field :event %>
  </div>
  <div class="field">
    <%= f.label :justification %>
    <%= f.text_area :justification, rows: 5 %>
  </div>
  <div class="field">
    <%= f.hidden_field :space_id %>
  </div>
</div>
<% end %>


<script type="text/javascript">
  $('.salvar').click(function() {
    $('form').submit();
  });
</script>

app/views/reserve_of_physical_spaces/reservas.html.erb
<h1>Reservas Fixas</h1>


 <table class="table">
 	<tr>
 		<th>Horário</th>
      <% for i in (1..31) %>
 		    <th><center><%= i %></center></th>
      <% end %>

 	</tr>
  <% for i in (0..15) %>
  <tr>
    <th><%= schedules[i] %></th>
    <% for j in (0..30) %>
      	<td><center><%= @array[i][j] %></center></td>
    <% end %>
  </tr>
  <% end %>
 </table>



 <%= link_to 'Reservar', new_reserve_of_physical_space_path(@id), class: 'btn btn-info' %>
 <%= link_to 'Voltar', reserve_of_physical_spaces_espacos_path, class: 'btn btn-info' %>