config/routes.rb
Transparencia::Application.routes.draw do

  resources :monthlies
  resources :travel_expenses
  resources :travel_drivers
  resources :travels
  resources :vehicles
  resources :drivers
  resources :participants
  resources :confirmations
  resources :requests
  resources :addresses
  resources :user_types
  resources :reserve_of_physical_spaces
  resources :reservation_statuses
  resources :alocation_permanents
  resources :spaces
  resources :location_types
  resources :semesters
  resources :recesses
  resources :holidays
  resources :request_users

  root to: 'users#login'

  # resources :administrators
  get '/administrator/login' => 'administrators#login', as: :administrator_login
  get '/administrator/logout' => 'administrators#logout', as: :administrator_logout
  get '/administrator/welcome' => 'administrators#welcome', as: :administrator_welcome
  post '/administrator/authentication' => 'administrators#authentication', as: :administrator_authentication
  post '/administrator/create' => 'administrators#create', as: :administrator_create
  get '/administrator/new' => 'administrators#new', as: :administrator_new

  #páginas de erro
  get '/notfound' => 'portal#notfound', as: :notfound
  
  resources :users do
    resources :durations
  end

  resources :roles
  resources :sectors
  resources :institutions
  resources :functions
  resources :locals
  resources :dailies
  resources :durations
  resources :daily_function_locals

  resources :amounts do
    resources :readjustments
  end

  resources :readjustments
  resources :requests

  get 'alocation_permanents/space/:semester_id/espacos' => 'alocation_permanents#espacos', as: 'alocation_permanents_espacos'
  get 'alocation_permanents/space/:id/:semester_id' => 'alocation_permanents#reserves', as: 'alocation_permanents_space'
  get 'alocation_permanents/space/:id/:semester_id/edit' => 'alocation_permanents#editar', as: 'alocation_permanents_editar'
  post 'alocation_permanents/spaces/:space_id/:semester_id/salvar_alocacao' => 'alocation_permanents#salvar_alocacao', as: 'salvar_alocacao'

  get 'reserve_of_physical_spaces/space/all' => 'reserve_of_physical_spaces#espacos', as: 'reserve_of_physical_spaces_espacos'
  get 'reserve_of_physical_spaces/space/:id' => 'reserve_of_physical_spaces#reservas', as: 'reserve_of_physical_spaces_reservas'
  get 'reserve_of_physical_spaces/space/:id/:mes/:ano' => 'reserve_of_physical_spaces#calendario', as: 'calendario'

  get 'reserve/space/:id/:mes/:ano/new' => 'reserve_of_physical_spaces#new', as: 'reserve_of_physical_spaces_reservas_new'
  
  get '/reserve_of_physical_spaces/aprovacoes/list' => 'reserve_of_physical_spaces#aprovacoes', as: 'aprovacoes'
  get '/reserve_of_physical_spaces/approve/:id' => 'reserve_of_physical_spaces#approve', as: 'approve_reserves'
  get '/reserve_of_physical_spaces/non_approve/:id' => 'reserve_of_physical_spaces#non_approve', as: 'non_approve_reserves'
  post '/create/:id/:mes/:ano/reserve_of_physical_space' => 'reserve_of_physical_spaces#create', as: 'create_reserve'
  post '/update/reserve_of_physical_space/:id' => 'reserve_of_physical_spaces#update', as: 'update_reserve'
  #post 'alocation_permanents/spaces/salvar_alocacao' => 'alocation_permanents#salvar_alocacao', as: 'salvar_alocacao'

  #rotas de users
  get '/user/login' => 'users#login', as: 'user_login'
  get '/user/logout' => 'users#logout', as: 'user_logout'
  post '/user/authentication' => 'users#authentication', as: 'user_authentication'
  get '/user/profile/edit' => 'users#edit_profile', as: 'edit_user_profile'
  get '/user/profile/edit/password' => 'users#edit_password', as: 'edit_user_password'
  post '/user/profile/update' => 'users#update_profile', as: 'update_user_profile'
  post '/user/profile/update/password' => 'users#update_password', as: 'update_user_password'

  
  #rotas de confirmations
  get '/confirmations/approve/:id' => 'confirmations#approve', as: 'approve_request'
  post '/confirmations/non_approve/:id' => 'confirmations#non_approve', as: 'non_approve_request'
  get '/confirmations/jus_non_approve/:id' => 'confirmations#non_approve_form', as: 'non_approve_form_request'

  #rota de participants para adicionar users a viagem 
  get '/participants/add/request/:id' => 'participants#index' ,as: 'add_participants'
  post '/participants/add/request/:id' => 'participants#add_participants' ,as: 'add_participants'
   
  #rota para solicitação
  get '/request/user' => 'requests#request_users', as: 'request_users'

  #rotas de confirmações
  get '/confirmations/:id/travel' => 'confirmations#travel', as: 'confirmation_travel'
  get '/confirmations/request/:id/travel/new' => 'travels#new', as: 'confirmation_new_travel'
  get '/confirmations/request/:id/travel/edit' => 'travels#edit', as: 'confirmation_edit_travel'
  get '/confirmations/:id/travel/show' => 'confirmations#show_travel', as: 'confirmation_show_travel'



  #rotas para adicionar motoristas a viagem
  get '/travels/:id/travel_drivers' => 'travel_drivers#index', as: 'add_driver'
  post '/travels/:id/travel_drivers' => 'travel_drivers#add_drivers', as: 'add_driver'
  resources :reserve_of_physical_spaces

  get '/relatorios/lista-de-veiculos' => 'reports#imprimir_veiculos', as: 'imprimir_veiculos'
  
  get '/home' => 'portal#index', as: 'home'
  get '/home/patrimonio' => 'portal#home_patrimonio', as: 'home_patrimonio'
  get '/home/transporte' => 'portal#home_transporte', as: 'home_transporte'
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  belongs_to :request
  belongs_to :user
  

  attr_accessible :user_id, 
                  :request_id,
                  :deleted


  #validates :user_id, presence: true
  #validades :request_id, presence: true

end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  
  def index
    @participant = User.new
    @participants = Participant.where(deleted: false, request_id: params[:id])
    @id = params[:id]
  end

  def add_participants
    @user = User.where(cpf: params[:user][:cpf]).first

    if @user.nil? == false
      participant = Participant.where(user_id: @user.id, request_id: params[:id]).first
      if participant.nil?
        Participant.create(user_id: @user.id, request_id: params[:id], deleted: false)      
      else
        participant.update_attributes(deleted: false)
      end
    end
    redirect_to add_participants_path(params[:id])
  end

  def show
    @participant = Participant.find(params[:id])
  end

  def new
    @participant = Participant.new
  end

  def edit
    @participant = Participant.find(params[:id])
  end

  def create
    @participant = Participant.new(params[:participant])

    if @participant.save
      redirect_to participants_path
    else
      render :edit
    end
  end

  def update
    @participant = Participant.find(params[:id])

    if @participant.update_attributes(params[:participant])
      redirect_to participants_path
    else
      render :edit
    end
  end

  def destroy
    @participant = Participant.find(params[:id])
    @participant.update_attribute(:deleted, true)
    redirect_to add_participants_path(@participant.request_id)
  end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.erb
<%= form_for(@participant) do |f| %>
  <% if @participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
      <% @participant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :request %><br />
    <%= f.text_field :request %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/participants/edit.html.erb
<h1>Editando Participante</h1>
<hr>
<%= render 'form' %>

app/views/participants/index.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="#">Adicionando Participantes</a>
    <ul class="nav">
      <%= form_for @participant, url: add_participants_path(@id), html: { class: 'navbar-form', style: 'display: inline' } do |f| %>
      <%= f.hidden_field :cpf %>
      <%= f.text_field :cpf , placeholder:'Digite CPF' %>
      <%= f.submit 'Buscar', class: 'btn'%>
      <%= link_to 'Voltar', requests_path, class: 'btn' %>
      <%end%>
    </ul>
  </div>
</div>

<table class="table table-hover">
  <tr>
    <th>Nome</th>
    <th>Matricula</th>
    <th>CPF</th>
    <th>Ações</th>
  </tr>

<% @participants.each do |p| %>
  <tr>
    <td><%= p.user.name %></td>
    <td><%= p.user.registration %></td>
    <td><%= p.user.cpf %></td>
    <td>
        
        <%= link_to p, method: :delete, data: { confirm: 'Você tem certeza?' }, title: 'Remover' do %><i class="icon-trash"></i><%end%>  
    </td>
  </tr>
<% end %>
</table>

<script type="text/javascript">
  $('.salvar').click(function() {
    $('form').submit();
  });
</script>

app/views/participants/new.html.erb
<h1>Novo participante</h1>
<hr>
<%= render 'form' %>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Request:</b>
  <%= @participant.request %>
</p>

<p>
  <b>User:</b>
  <%= @participant.user %>
</p>


<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>