config/routes.rb
Transparencia::Application.routes.draw do

  resources :monthlies
  resources :travel_expenses
  resources :travel_drivers
  resources :travels
  resources :vehicles
  resources :drivers
  resources :participants
  resources :confirmations
  resources :requests
  resources :addresses
  resources :user_types
  resources :reserve_of_physical_spaces
  resources :reservation_statuses
  resources :alocation_permanents
  resources :spaces
  resources :location_types
  resources :semesters
  resources :recesses
  resources :holidays
  resources :request_users

  root to: 'users#login'

  # resources :administrators
  get '/administrator/login' => 'administrators#login', as: :administrator_login
  get '/administrator/logout' => 'administrators#logout', as: :administrator_logout
  get '/administrator/welcome' => 'administrators#welcome', as: :administrator_welcome
  post '/administrator/authentication' => 'administrators#authentication', as: :administrator_authentication
  post '/administrator/create' => 'administrators#create', as: :administrator_create
  get '/administrator/new' => 'administrators#new', as: :administrator_new

  #páginas de erro
  get '/notfound' => 'portal#notfound', as: :notfound
  
  resources :users do
    resources :durations
  end

  resources :roles
  resources :sectors
  resources :institutions
  resources :functions
  resources :locals
  resources :dailies
  resources :durations
  resources :daily_function_locals

  resources :amounts do
    resources :readjustments
  end

  resources :readjustments
  resources :requests

  get 'alocation_permanents/space/:semester_id/espacos' => 'alocation_permanents#espacos', as: 'alocation_permanents_espacos'
  get 'alocation_permanents/space/:id/:semester_id' => 'alocation_permanents#reserves', as: 'alocation_permanents_space'
  get 'alocation_permanents/space/:id/:semester_id/edit' => 'alocation_permanents#editar', as: 'alocation_permanents_editar'
  post 'alocation_permanents/spaces/:space_id/:semester_id/salvar_alocacao' => 'alocation_permanents#salvar_alocacao', as: 'salvar_alocacao'

  get 'reserve_of_physical_spaces/space/all' => 'reserve_of_physical_spaces#espacos', as: 'reserve_of_physical_spaces_espacos'
  get 'reserve_of_physical_spaces/space/:id' => 'reserve_of_physical_spaces#reservas', as: 'reserve_of_physical_spaces_reservas'
  get 'reserve_of_physical_spaces/space/:id/:mes/:ano' => 'reserve_of_physical_spaces#calendario', as: 'calendario'

  get 'reserve/space/:id/:mes/:ano/new' => 'reserve_of_physical_spaces#new', as: 'reserve_of_physical_spaces_reservas_new'
  
  get '/reserve_of_physical_spaces/aprovacoes/list' => 'reserve_of_physical_spaces#aprovacoes', as: 'aprovacoes'
  get '/reserve_of_physical_spaces/approve/:id' => 'reserve_of_physical_spaces#approve', as: 'approve_reserves'
  get '/reserve_of_physical_spaces/non_approve/:id' => 'reserve_of_physical_spaces#non_approve', as: 'non_approve_reserves'
  post '/create/:id/:mes/:ano/reserve_of_physical_space' => 'reserve_of_physical_spaces#create', as: 'create_reserve'
  post '/update/reserve_of_physical_space/:id' => 'reserve_of_physical_spaces#update', as: 'update_reserve'
  #post 'alocation_permanents/spaces/salvar_alocacao' => 'alocation_permanents#salvar_alocacao', as: 'salvar_alocacao'

  #rotas de users
  get '/user/login' => 'users#login', as: 'user_login'
  get '/user/logout' => 'users#logout', as: 'user_logout'
  post '/user/authentication' => 'users#authentication', as: 'user_authentication'
  get '/user/profile/edit' => 'users#edit_profile', as: 'edit_user_profile'
  get '/user/profile/edit/password' => 'users#edit_password', as: 'edit_user_password'
  post '/user/profile/update' => 'users#update_profile', as: 'update_user_profile'
  post '/user/profile/update/password' => 'users#update_password', as: 'update_user_password'

  
  #rotas de confirmations
  get '/confirmations/approve/:id' => 'confirmations#approve', as: 'approve_request'
  post '/confirmations/non_approve/:id' => 'confirmations#non_approve', as: 'non_approve_request'
  get '/confirmations/jus_non_approve/:id' => 'confirmations#non_approve_form', as: 'non_approve_form_request'

  #rota de participants para adicionar users a viagem 
  get '/participants/add/request/:id' => 'participants#index' ,as: 'add_participants'
  post '/participants/add/request/:id' => 'participants#add_participants' ,as: 'add_participants'
   
  #rota para solicitação
  get '/request/user' => 'requests#request_users', as: 'request_users'

  #rotas de confirmações
  get '/confirmations/:id/travel' => 'confirmations#travel', as: 'confirmation_travel'
  get '/confirmations/request/:id/travel/new' => 'travels#new', as: 'confirmation_new_travel'
  get '/confirmations/request/:id/travel/edit' => 'travels#edit', as: 'confirmation_edit_travel'
  get '/confirmations/:id/travel/show' => 'confirmations#show_travel', as: 'confirmation_show_travel'



  #rotas para adicionar motoristas a viagem
  get '/travels/:id/travel_drivers' => 'travel_drivers#index', as: 'add_driver'
  post '/travels/:id/travel_drivers' => 'travel_drivers#add_drivers', as: 'add_driver'
  resources :reserve_of_physical_spaces

  get '/relatorios/lista-de-veiculos' => 'reports#imprimir_veiculos', as: 'imprimir_veiculos'
  
  get '/home' => 'portal#index', as: 'home'
  get '/home/patrimonio' => 'portal#home_patrimonio', as: 'home_patrimonio'
  get '/home/transporte' => 'portal#home_transporte', as: 'home_transporte'
end

app/controllers/location_types_controller.rb
class LocationTypesController < ApplicationController

  include UsersHelper
  
  # before_filter :autorizacao_chefe_setor_patrimonio, except: []

  def index
    @location_types = LocationType.where(deleted: false)
  end

  def show
    @location_type = LocationType.find(params[:id])
  end

  def new
    @location_type = LocationType.new
  end

  def edit
    @location_type = LocationType.find(params[:id])
  end

  def create
    @location_type = LocationType.new(params[:location_type])
    @location_type.deleted = false

    if @location_type.save
      redirect_to location_types_path
    else
      render :new
    end    
  end

  def update
    @location_type = LocationType.find(params[:id])

    if @location_type.update_attributes(params[:location_type])
      redirect_to location_types_path
    else
      render :edit  
    end
  end

  def destroy
    @location_type = LocationType.find(params[:id])
    @location_type.update_attribute(:deleted, true)
    redirect_to location_types_path
  end
end

app/helpers/location_types_helper.rb
module LocationTypesHelper
end

app/views/location_types/_form.html.erb
<%= form_for @location_type do |f| %>
  <% if @location_type.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @location_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="espacamento">
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, autofocus: 'autofocus' %>
    </div>
  </div>
<% end %>

<script type="text/javascript">
  $('.salvar').click(function() {
    $('form').submit();
  });
</script>

app/views/location_types/edit.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="#">Editando tipo de espaço</a>
    <ul class="nav">
      <li><%= link_to 'Salvar', '#', class: 'salvar' %></li>
      <li><%= link_to 'Cancelar', location_types_path %></li>
    </ul>
  </div>
</div>

<%= render 'form' %>

app/views/location_types/index.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="#">Tipos de Espaços</a>
    <ul class="nav">
      <li><%= link_to 'Criar novo', new_location_type_path %></li>
    </ul>
  </div>
</div>

<div class="espacamento">
  <table class="table table-hover">
    <tr>
      <th>Nome</th>
      <th width="80">Ações</th>
    </tr>

  <% @location_types.each do |location_type| %>
    <tr>
      <td><%= location_type.name %></td>
      <td>
        <%= link_to edit_location_type_path(location_type), title: 'Editar' do %><i class="icon-edit"></i><% end %>
        <%= link_to location_type, method: :delete, data: { confirm: 'Você tem certeza?' }, title: 'Remover' do %><i class="icon-trash"></i> <% end %>
      </td>
    </tr>
  <% end %>
  </table>
</div>

app/views/location_types/new.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="#">Novo tipo de espaço</a>
    <ul class="nav">
      <li><%= link_to 'Salvar', '#', class: 'salvar' %></li>
      <li><%= link_to 'Cancelar', location_types_path %></li>
    </ul>
  </div>
</div>

<%= render 'form' %>

app/views/location_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @location_type.name %>
</p>